name = "KitBase"
uuid = "86eed249-3a28-466f-8d3a-596821e1af9a"
authors = ["Tianbai Xiao <tianbaixiao@gmail.com>"]
version = "0.9.22"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FiniteMesh = "d3ebd857-6980-4843-ad12-8da20c4645b4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SciMLNLSolve = "e9a6253c-8580-4d32-9898-8661bb511710"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TypedPolynomials = "afbbf031-7a57-5f58-a1b9-b774a0fad08d"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
BSON = "0.3"
CSV = "0.8, 0.9, 0.10"
CUDA = "^2, ^3, ^4, ^5"
Distributions = "0.21, 0.22, 0.23, 0.24, 0.25"
FFTW = "^1"
FastGaussQuadrature = "0.2, 0.3, 0.4, 0.5, ^1"
FileIO = "^1"
FiniteMesh = "0.3"
ForwardDiff = "0.10"
JLD2 = "0.4"
MultivariatePolynomials = "0.3, 0.4, 0.5"
NonlinearSolve = "^1, ^2, ^3"
OffsetArrays = "^1"
Optim = "^1"
Parameters = "0.12"
RecipesBase = "^1"
Reexport = "^1"
Roots = "^2"
SciMLNLSolve = "0.1"
SpecialFunctions = "0.7, 0.8, 0.9, 0.10, ^1, ^2"
StaticArrays = "^1"
StructArrays = "0.5, 0.6"
TypedPolynomials = "0.2, 0.3, 0.4"
WriteVTK = "^1"
julia = "^1"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots"]
