name = "KitBase"
uuid = "86eed249-3a28-466f-8d3a-596821e1af9a"
authors = ["Tianbai Xiao <tianbaixiao@gmail.com>"]
version = "0.6.9"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FiniteMesh = "d3ebd857-6980-4843-ad12-8da20c4645b4"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TypedPolynomials = "afbbf031-7a57-5f58-a1b9-b774a0fad08d"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
CSV = "0.8"
CUDA = "^2, ^3"
Conda = "^1"
Distributions = "0.21, 0.22, 0.23, 0.24, 0.25"
FFTW = "^1"
FastGaussQuadrature = "0.2, 0.3, 0.4"
FileIO = "^1"
FiniteMesh = "0.3"
JLD2 = "0.1, 0.2, 0.3, 0.4"
MultivariatePolynomials = "0.3"
OffsetArrays = "1.8"
Optim = "^1"
Plots = "^1"
ProgressMeter = "^1"
PyCall = "^1"
Reexport = "^1"
SpecialFunctions = "0.7, 0.8, 0.9, 0.10, 1.0"
StaticArrays = "^1"
StructArrays = "0.5, 0.6"
TypedPolynomials = "0.2"
WriteVTK = "^1"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
